import "./globals.scss";
import Header from "./components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
          <Header />
          {children}
        </body>
    </html>
  );
}
