import "./globals.scss";
import Header from "./components/Header";
import { Providers } from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>
        <div
          className="fixed bottom-0 -left-0 z-0 w-full h-full bg-bottom bg-no-repeat bg-contain"
          style={{
            backgroundImage: "url(/bg-1.png)",
            transform: "translate(-35%, 20%)",
          }}
        >
        </div>
        <div
          className="fixed top-0 right z-0 w-full h-full bg-bottom bg-no-repeat bg-contain"
          style={{
            backgroundImage: "url(/bg-2.png)",
            transform: "translate(10%, -10%)",
          }}
        >
        </div>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
